"""Add description column to nodes.

Revision ID: 3b1b31641ba5
Revises:
Create Date: 2024-11-27 20:04:05.887447

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3b1b31641ba5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("description", sa.String(), nullable=False))
    op.add_column("nodes", sa.Column("order", sa.Integer(), nullable=False))
    op.drop_constraint("nodes_roadmap_id_fkey", "nodes", type_="foreignkey")
    op.create_foreign_key(None, "nodes", "roadmaps", ["roadmap_id"], ["id"])
    op.alter_column("roadmaps", "skill_level",
               existing_type=postgresql.ENUM("beginner", "intermediate", "advanced", name="skill_level_enum"),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roadmaps", "skill_level",
               existing_type=postgresql.ENUM("beginner", "intermediate", "advanced", name="skill_level_enum"),
               nullable=True)
    op.drop_constraint(None, "nodes", type_="foreignkey")
    op.create_foreign_key("nodes_roadmap_id_fkey", "nodes", "roadmaps", ["roadmap_id"], ["id"], ondelete="CASCADE")
    op.drop_column("nodes", "order")
    op.drop_column("nodes", "description")
    # ### end Alembic commands ###
