"""Add description column to nodes.

Revision ID: 55653b0b0b5d
Revises: 3b1b31641ba5
Create Date: 2024-11-27 20:04:47.375301

"""
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "55653b0b0b5d"
down_revision: str | None = "3b1b31641ba5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
