"""Add label_id to Node model.

Revision ID: 7ed55411d823
Revises: f3966b25cde9
Create Date: 2025-03-28 23:46:17.500516

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7ed55411d823'
down_revision: str | None = 'f3966b25cde9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed incorrect drop_table operations
    op.add_column('nodes', sa.Column('label_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_nodes_label_id'), 'nodes', ['label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_label_id'), table_name='nodes')
    op.drop_column('nodes', 'label_id')
    # Removed incorrect create_table operations
    # ### end Alembic commands ###
