"""add status to nodes.

Revision ID: f3966b25cde9
Revises: 55653b0b0b5d
Create Date: 2024-11-27 20:29:27.416537

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f3966b25cde9"
down_revision: str | None = "55653b0b0b5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "status")
    # ### end Alembic commands ###
